version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:15.2-alpine
    restart: "no"
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
