"""add relationship

Revision ID: c3fedba935af
Revises: e2610bf8e4ef
Create Date: 2023-05-25 17:25:48.223236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fedba935af'
down_revision = 'e2610bf8e4ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
